pipeline {
    agent any
    stages {
        stage("Set Working Directory") {
            agent {
                docker {
                    reuseNode true
                    image 'node:alpine'
                }
            }
            steps {
                sh '''
                node -v
                cd ui_testing
                '''
            }
        }
        stage("Install dependencies") {
            steps {
                sh 'npm ci'
            }
        }
        stage("UI Testing") {
            steps {
                sh 'npm test'
            }
        }
    }
}
