pipeline {
    agent any
    tools { nodejs 'node' }
    environment {
        CYPRESS_BASE_URL = '$FRONTEND_URL'
    }
    stages {
        stage('Install dependencies') {
            steps {
                dir('ui_testing') {
                    sh 'npm ci'
                }
            }
        }
        stage('UI Testing') {
            steps {
                dir('ui_testing') {
                    sh 'npm test'
                }
            }
        }
        stage('Publish report') {
            steps {
                publishHTML (
                    target : [
                        alwaysLinkToLastBuild: true,
                        reportDir: 'ui_testing/cypress/reports',
                        reportFiles: 'report.html',
                        reportName: 'UI Test Report'
                    ]
                )
            }
        }
    }
}
